### PR TITLE
Remove UUID dependency in favour of own key generation system

### LINKED ISSUE #10: Error: getRandomValues() not supported
Affects `1.0.6` - upon launching app, I see the following error:

Screen Shot 2020-08-18 at 12 54 24 am

In my use case, I have some screens where I have two instances of Modalize - in other screens just one.

This issue can be fixed by the developer by following the steps at: https://github.com/uuidjs/uuid#getrandomvalues-not-supported as a polyfill is required for `uuid` to work in RN

Related to the fix in #9, which was a PR originally created to fix #7

### PR DESCRIPTION
**Pull request by harveyappleton**
Hey @jeremybarbet, did some tweaking to generate our own solution to this.

Really happy if you'd rather go with UUID route.

But in summary, this:
- keeps track of used keys,
- retries if it hits a duplicate (up to 5 times, but thats such an edge case as it's so random it should be fine, just wanted to stop an endless loop of retries)
- removes used keys on unmount

And doesn't have any external dependencies.
Should fix #10 too

Let me know your thoughts or if my code could be better :-)

Thanks bossman

### CODE REVIEW

File: src/Host.tsx [hunk 1]
```diff
@@ -44,8 +44,36 @@ export const Host = ({ children, style }: IHostProps): JSX.Element => {
     }
   }, []);
 
-  const mount = (children: React.ReactNode): number => {
-    const key = Date.now();
+  //Keep track of all the keys we've generated to ensure uniqueness
+  let usedKeys: Array<string> = [];
+
+  //Makes a magical random key
+  const keyGenerator = (): string => {
```
Comment (jeremybarbet) [inline src/Host.tsx:51]: Can we move this function into a separated file? best would be `utils/file_name.ts`

File: src/Host.tsx [hunk 2]
```diff
@@ -44,8 +44,36 @@ export const Host = ({ children, style }: IHostProps): JSX.Element => {
...
+      .toString(36)
+      .substr(2, 16)}-${Math.random().toString(36).substr(2, 16)}`;
+  };
+
+  //Keeps making new keys until a unique one has been found
+  const getNewKey = (): string => {
+    let foundUniqueKey = false;
+    let newKey = '';
+    let tries = 0;
+    while (!foundUniqueKey && tries < 5) {
```
Comment (jeremybarbet) [inline src/Host.tsx:62]: What happen when we didn't find a unique key after 5 tries, we get an empty string?

**Review by jeremybarbet — CHANGES_REQUESTED** [review]
Hey!

Could you rebase against master? your changes already merged are also here.

File: src/Host.tsx (hunk 2 above)
Comment (harveyappleton) [reply src/Host.tsx:62]: > What happen when we didn't find a unique key after 5 tries, we get an empty string?

Yeah.. totally open to suggestions here as to what our fallback key should be! The 'randomness' of the key generation probably means its super unlikely to have even 1 clash, let alone 5. But I agree, we should have some sort of fall back to something. Any ideas?

File: src/Host.tsx (hunk 1 above)
Comment (harveyappleton) [reply src/Host.tsx:51]: > Can we move this function into a separated file? best would be `utils/file_name.ts`

Yep makes total sense!

Also, question: I wondered whether the usedKeys array should really be stored in a ref, otherwise on every re-render of the Host, we're going to reset that array surely?

File: src/Host.tsx (hunk 2 above)
Comment (jeremybarbet) [reply src/Host.tsx:62]: Maybe 5 tries is too much, if it's super unlikely. Can we start with 3? 

Yes, let's fallback to Date.now() ahahah

File: src/Host.tsx (hunk 1 above)
Comment (jeremybarbet) [reply src/Host.tsx:51]: Okay better then, we could export it under hooks/useGeneratedKey.ts where it keeps the ref there for the usedKeys and have the logic there

File: src/Host.tsx (hunk 2 above)
Comment (harveyappleton) [reply src/Host.tsx:62]: This is hilarious! haha ok no worries. Im sure we could 'work out' the probability of hitting 3 times, but I think its sooo unlikely

File: src/Host.tsx (hunk 1 above)
Comment (harveyappleton) [reply src/Host.tsx:51]: OK I shall work on that :) writing in TypeScript is fairly new to me, so bear with!

**Comment by harveyappleton** [comment]
> Could you rebase against master? your changes already merged are also here.

I think I've rebased correctly! Please have a look :-) 
Next task is to work on utils/key gen :)

**Comment by harveyappleton** [comment]
@jeremybarbet I've created external hook: hooks/useGeneratedKey.ts 
The array of used keys doesn't need to be a ref because it's not stored within a React component that re-renders (just stored at the top of the hook file).

Testing seems to show all working! 
Attached is screenshot of it adding keys. It removes them successfully too.

No clashes yet (you can see how random the keys are!)

Let me know your thoughts :-)
Screenshot 2020-08-18 at 13 05 53

File: src/Host.tsx [hunk 3]
```diff
@@ -1,6 +1,6 @@
 import * as React from 'react';
 import { View, ViewStyle } from 'react-native';
-
+import { useGeneratedKey, removeKey } from './hooks/useGeneratedKey';
```
Comment (jeremybarbet) [inline src/Host.tsx:3]: One line-break

```suggestion

import { useGeneratedKey, removeKey } from './hooks/useGeneratedKey';
```

File: src/hooks/useGeneratedKey.ts [hunk 4]
```diff
@@ -0,0 +1,37 @@
+//Keep track of all the keys we've generated to ensure uniqueness
+let usedKeys: Array<string> = [];
```
Comment (jeremybarbet) [inline src/hooks/useGeneratedKey.ts:2]: I think we would need to keep a reference to this array, not entirely sure 🧐. I would probably move it inside the function useGeneratedKey with a 

```tsx
const usedKeys = useRef<Array<string>>([]);
```

and then further used as `usedKeys.current.push()`

File: src/hooks/useGeneratedKey.ts [hunk 5]
```diff
@@ -0,0 +1,37 @@
...
+
+//Generates a random key
+const keyGenerator = (): string => {
+  return `portalize_${Math.random().toString(36).substr(2, 16)}-${Math.random()
+    .toString(36)
+    .substr(2, 16)}-${Math.random().toString(36).substr(2, 16)}`;
+};
+
+//Custom hook that checks for uniqueness and retries if clashes
```
Comment (jeremybarbet) [inline src/hooks/useGeneratedKey.ts:11]: Can you add a space after the comment char

```suggestion
// Custom hook that checks for uniqueness and retries if clashes
```

File: src/hooks/useGeneratedKey.ts [hunk 6]
```diff
@@ -0,0 +1,37 @@
...
+  if (!foundUniqueKey) {
+    newKey = `portalize_${Date.now()}_${Math.floor(Math.random() * 1000)}`; //fallback method
+  }
+
+  usedKeys.push(newKey);
+  return newKey;
+};
+
+//Removes our key to make it 'available' again
+export const removeKey = (key: string): null => {
```
Comment (jeremybarbet) [inline src/hooks/useGeneratedKey.ts:34]: I would move that as a function inside useGeneratedKey. I would probably rename it to `useKey` that return two functions

```tsx
const { generateKey, removeKey } = useKey();
...
const key = generateKey();
```

File: src/hooks/useGeneratedKey.ts [hunk 7]
```diff
@@ -0,0 +1,37 @@
...
+//Generates a random key
+const keyGenerator = (): string => {
+  return `portalize_${Math.random().toString(36).substr(2, 16)}-${Math.random()
+    .toString(36)
+    .substr(2, 16)}-${Math.random().toString(36).substr(2, 16)}`;
+};
+
+//Custom hook that checks for uniqueness and retries if clashes
+export const useGeneratedKey = (): string => {
+  let foundUniqueKey = false;
```
Comment (jeremybarbet) [inline src/hooks/useGeneratedKey.ts:13]: We should also try to use refs here for the `lets`

**Review by jeremybarbet — CHANGES_REQUESTED** [review]

**Comment by harveyappleton** [comment]
@jeremybarbet I've refactored as you've requested 👍 

Only thing to note is there's no benefit to using Refs for the lets inside generate key, as they are all block-level scoped to the generateKey function and just used to generate the key temporarily. Is that ok?

Would love to know your thoughts on if my first dip into typescript went well!!

File: src/hooks/useKey.ts [hunk 8]
```diff
@@ -0,0 +1,46 @@
...
+
+// Custom hook that checks for uniqueness and retries if clashes
+export const useKey = (): IUseKey => {
+  const usedKeys = React.useRef<Array<string>>([]);
+
+  const generateKey = (): string => {
+    let foundUniqueKey = false;
+    let newKey = '';
+    let tries = 0;
+    while (!foundUniqueKey && tries < 3) {
```
Comment (jeremybarbet) [inline src/hooks/useKey.ts:23]:
```suggestion

    while (!foundUniqueKey && tries < 3) {
```

File: src/hooks/useKey.ts [hunk 9]
```diff
@@ -0,0 +1,46 @@
...
+      //limit number of tries to stop endless loop of pain
```
Comment (jeremybarbet) [inline src/hooks/useKey.ts:24]:
```suggestion
      // limit number of tries to stop endless loop of pain
```

File: src/hooks/useKey.ts [hunk 10]
```diff
@@ -0,0 +1,46 @@
...
+      tries++;
+      newKey = keyGenerator();
+      if (!usedKeys.current.includes(newKey)) {
```
Comment (jeremybarbet) [inline src/hooks/useKey.ts:27]:
```suggestion

      if (!usedKeys.current.includes(newKey)) {
```

File: src/hooks/useKey.ts [hunk 11]
```diff
@@ -0,0 +1,46 @@
...
+        foundUniqueKey = true;
+      }
+    }
+    //will only run if exited while loop without finding a unique key
```
Comment (jeremybarbet) [inline src/hooks/useKey.ts:31]:
```suggestion

    // will only run if exited while loop without finding a unique key
```

File: src/hooks/useKey.ts [hunk 12]
```diff
@@ -0,0 +1,46 @@
...
+    if (!foundUniqueKey) {
+      newKey = `portalize_${Date.now()}_${Math.floor(Math.random() * 1000)}`; //fallback method
```
Comment (jeremybarbet) [inline src/hooks/useKey.ts:33]:
```suggestion
      newKey = `portalize_${Date.now()}_${Math.floor(Math.random() * 1000)}`; // fallback method
```

**Review by jeremybarbet — CHANGES_REQUESTED** [review]
Yes you are right, it's should be good like this, these variables aren't accessed in any other way.

I have only a few comments on the code style. Sorry I'm super picky on the coding guideline 🤓

It looks all good now and the hook looks neat! Hopefully, we won't get the issue anymore after that :)

**Comment by harveyappleton** [comment]
> I have only a few comments on the code style. Sorry I'm super picky on the coding guideline 🤓

No worries! Just committed all your suggestions, take a look and make sure youre happy :-)

**Comment by jeremybarbet** [comment]
Looks good now, I will release a new version and you can test it out! Thanks for your contribution! 

Edit: Released in `1.0.7`

**Comment by edc123** [comment]
Hi @jeremybarbet - this seems to work great in all use cases I have in my app upon updating to `1.0.7` and removing the dep on the polyfill. I'm looking at that fresh issue  (#12) but not sure what the scenario is, but perhaps we should check if that was under an earlier version. Great work @harveyappleton @jeremybarbet ! Thank you

**Comment by benjaminreid** [comment]
Yes, nice work chaps. I ran into a very similar issue with two modals on one screen and updating to `1.0.7` has fixed things for me.
